# Site settings
title: El Maná
email: elmanadefuengirola@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
keywords: "your keywords, separated by commas"
meta_author: El Maná

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:


# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: elmanafuengirola

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: AF7AC5 #80B3FF
  primary-rgb: "175,122,197"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: El Maná, Creado por yaniramartindev.com
  location: Localización
  social: Redes sociales
  credits: Horarios

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/elmanafuengirola/
  - title: facebook
    url: https://www.facebook.com/ElManaFuengirola
  - title: tripadvisor
    svg: tripadvisor.svg
    url: https://www.tripadvisor.es/Restaurant_Review-g315915-d20471600-Reviews-El_Mana-Fuengirola_Costa_del_Sol_Province_of_Malaga_Andalucia.html
  - title: whatsapp
    svg: whatsapp.svg
    url: https://api.whatsapp.com/send?phone=34633327444?text=Hola%20quiero%20reservar%20...

# Postal address (add as many lines as necessary)
address:
  - line: Calle Castillo, 7
  - line: 29640 Fuengirola, Málaga

# Credits content
credits: 'Viernes, Sábado y Domingo desde las 17:00 h. Lunes, Miércoles y Jueves desde las 18:00 h.'

# Build settings
markdown: kramdown
permalink: pretty
